import tensorflow as tf

treenet_timeseries_extended = {
    "data/timeseries_input": tf.io.FixedLenFeature([], tf.string),
    "label/timeseries_label": tf.io.FixedLenFeature([], tf.string),
    "label/series_id": tf.io.FixedLenFeature([], tf.int16),
    "label/site_id": tf.io.FixedLenFeature([], tf.int16),
    "label/tree_xcor": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_ycor": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_altitude": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_genus": tf.io.FixedLenFeature([], tf.string),
    "label/tree_species": tf.io.FixedLenFeature([], tf.string),
    "label/tree_dbh": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_height": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_totalbark_thickness_mm": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_twd_max_gp": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_tree_twd_med_gp": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_twd_max_nogp": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_twd_med_nogp": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_gro_start_doy_med": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_gro_end_doy_med": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_gro_max_yr": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_gro_med_yr": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_gro_min_yr": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_gro_med_month": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_gro_med_week": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_gro_med_day": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_gro_med_hr": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_timing_gro_week_max": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_timing_gro_hour_max": tf.io.FixedLenFeature([], tf.float32),
    "label/tree_grohours_med": tf.io.FixedLenFeature([], tf.float32),
    "label/site_name": tf.io.FixedLenFeature([], tf.string),
    "label/site_exposition": tf.io.FixedLenFeature([], tf.string),
    "label/site_ycor": tf.io.FixedLenFeature([], tf.float32),
    "label/site_altitude": tf.io.FixedLenFeature([], tf.float32),
    "label/site_forest_type": tf.io.FixedLenFeature([], tf.string),
    "label/site_soil_type": tf.io.FixedLenFeature([], tf.string),
    "label/region": tf.io.FixedLenFeature([], tf.string),
    "label/country": tf.io.FixedLenFeature([], tf.string),
    "label/site_annual_temp": tf.io.FixedLenFeature([], tf.float32),
    "label/site_annual_precip": tf.io.FixedLenFeature([], tf.float32),
}

treenet_timeseries_short = {
    "data/timeseries_input": tf.io.FixedLenFeature([], tf.string),
    "data/timeseries_label": tf.io.FixedLenFeature([], tf.string),
    "other/min_values": tf.io.FixedLenFeature([], tf.string),
    "other/differences": tf.io.FixedLenFeature([], tf.string),
    "other/shape": tf.io.FixedLenFeature([2], tf.int64),
    }