python3 1_make_segments_from_raw_data.py \
  --out_root /home/lukovic/data/treenet/outputs_30d \
  --metadata_pickle /storage/lukovic/Data/FORWARDS/treenet/server_data/metadata_all.pkl \
  --meteo_dir       /storage/lukovic/Data/FORWARDS/treenet/meteo_data \
  --thermo_dir      /storage/lukovic/Data/FORWARDS/treenet/server_data/thermometer_l1 \
  --hygro_dir       /storage/lukovic/Data/FORWARDS/treenet/server_data/hygrometer_l1 \
  --dendro_l2_dir   /storage/lukovic/Data/FORWARDS/treenet/server_data/dendrometer_l2 \
  --dendro_lm_dir   /storage/lukovic/Data/FORWARDS/treenet/server_data/dendrometer_lm \
  --train_site_ids_csv /home/lukovic/data/treenet/train_sites_temp.csv\
  --test_site_ids_csv  /home/lukovic/data/treenet/test_sites_temp.csv \
  --years 2019 \
  --window_days 30 \
  --stride_days_after_accept 10
